spring:
  application:
    name: quotecraft-apis

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/quotecraft}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
app:
  cors:
    allowed-origin: ${FRONTEND_ORIGIN:http://localhost:5173}
  jwt:
    secret: ${JWT_SECRET:change-me-to-a-very-long-secret-key-for-dev-only-123456}
    expiration-minutes: ${JWT_EXP_MINUTES:120}
google:
  client:
    id: ${GOOGLE_CLIENT_ID}